### ISSUE TITLE
New hashable dict data structure

### ISSUE THREAD

**Issue by tristan0x** [cogniteev/docido-python-sdk#34]
```python
class hashabledict(dict):
    def __hash__(self):
        return hash(tuple(sorted(self.items()))
```

Also fix the invalid hash function used in Mongo connections pool.

**Comment by phildav** [comment]
I took that from a stackoverflow topic, but the `__hash__()` proposed does not handle nested dicts. `dict_hash` in oncrawl-api does handle nested dict but is probably heavier.
